### ISSUE TITLE
Missing install_requirements.sh 

### ISSUE THREAD

**Issue by noahmcdonaldj304** [catalys1/fractal-pretraining#1]
Hello,

I would like to work with this code.
I cloned the github and started the setup, however the file install_requirements.sh is not to be found.
Am I missing something? any help would be appreciated.

**Comment by catalys1** [comment]
You're correct, it doesn't appear to be there. I'm not quite sure what happened. I'll look into it.

**Comment by catalys1** [comment]
@noahmcdonaldj304 It looks like it never got committed. I've added it now. Sorry about the confusion!
