### ISSUE TITLE
Would you set a license for your fractal-pretraining repo?

### ISSUE THREAD

**Issue by akh1r0ck** [catalys1/fractal-pretraining#3]
Hi, please accept my apologies for reaching out unexpectedly. 

According to Github License rule as below, when we try clone your repo, we need to have any license that allows us to clone your repo like MIT, Apapche, and CCYB.
If you mind us to exec "git clone" and we use your code for our study / develop actions, set the license on your repo.

https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository

Thank you in advance.

**Comment by catalys1** [comment]
Done. Thanks!
